#!/bin/bash
good=0
bad=0
TIMOUT=`expr 570000 / ${BAUD_RATE} + 3`
i=0
while [ $i -lt 40 ]
do
 timeout --signal=SIGKILL ${TIMOUT} $*
 ##$*
 if [ $? -eq 0 ]
 then
  good=`expr $good + 1`
 else
  bad=`expr $bad + 1`
 fi
 i=`expr $i + 1`
 echo "                                                      "
 echo "Versuch ${i} von 40 für Freq ${FRQ}, ${bad} fehlerhaft"
 echo "                                                      "
done
echo "$good good, $bad fail"
echo "${FRQ} $bad" >> ${Prefix}_${BAUD_RATE}_${SERCHIP}_${TSB}.tab
