LISTE1 = ../GNU/Cap_FC_dataEN.pdf
LISTE1 += ../GNU/Cap_FR_dataEN.pdf
LISTE1 += ../GNU/Cap_FC_FR_dataEN.pdf
LISTE1 += ../GNU/CesrEN.pdf
LISTE1 += ../GNU/Cesr2EN.pdf
LISTE1 += ../GNU/Cesr_22nEN.pdf
LISTE1 += ../GNU/Cesr_22n_lowEN.pdf
LISTE1 += ../GNU/ComparatorAdjustEN.pdf
LISTE1 += ../GNU/Elco_esrEN.pdf
LISTE1 += ../GNU/frequency-ppmEN.pdf
LISTE1 += ../GNU/induct328pEN.pdf
LISTE1 += ../GNU/m168res_allEN.pdf
LISTE1 += ../GNU/MegaAutoEN.pdf
LISTE1 += ../GNU/Mega1284EN.pdf
LISTE1 += ../GNU/Mega168allEN.pdf 
LISTE1 += ../GNU/Mega168capEN.pdf
LISTE1 += ../GNU/Mega168cap_optEN.pdf
LISTE1 += ../GNU/Mega328allEN.pdf
LISTE1 += ../GNU/Mega8capEN.pdf
LISTE1 += ../GNU/Mega8resEN.pdf
LISTE1 += ../GNU/res_esrEN.pdf
LISTE1 += ../GNU/RHvEN.pdf
LISTE1 += ../GNU/RLvhighEN.pdf
LISTE1 += ../GNU/RLvlowEN.pdf
LISTE1 += ../GNU/RLvtotEN.pdf
LISTE1 += ../GNU/SelfTrefEN.pdf
LISTE1 += ../GNU/W12compareEN.pdf

LISTE2 = ../GNU/Cap_FC_dataCZ.pdf
LISTE2 += ../GNU/Cap_FR_dataCZ.pdf
LISTE2 += ../GNU/Cap_FC_FR_dataCZ.pdf
LISTE2 += ../GNU/CesrCZ.pdf
LISTE2 += ../GNU/Cesr2CZ.pdf
LISTE2 += ../GNU/Cesr_22nCZ.pdf
LISTE2 += ../GNU/Cesr_22n_lowCZ.pdf
LISTE2 += ../GNU/ComparatorAdjustCZ.pdf
LISTE2 += ../GNU/Elco_esrCZ.pdf
LISTE2 += ../GNU/frequency-ppmCZ.pdf
LISTE2 += ../GNU/induct328pCZ.pdf
LISTE2 += ../GNU/m168res_allCZ.pdf
LISTE2 += ../GNU/MegaAutoCZ.pdf
LISTE2 += ../GNU/Mega1284CZ.pdf
LISTE2 += ../GNU/Mega168allCZ.pdf 
LISTE2 += ../GNU/Mega168capCZ.pdf
LISTE2 += ../GNU/Mega168cap_optCZ.pdf
LISTE2 += ../GNU/Mega328allCZ.pdf
LISTE2 += ../GNU/Mega8capCZ.pdf
LISTE2 += ../GNU/Mega8resCZ.pdf
LISTE2 += ../GNU/res_esrCZ.pdf
LISTE2 += ../GNU/RHvCZ.pdf
LISTE2 += ../GNU/RLvhighCZ.pdf
LISTE2 += ../GNU/RLvlowCZ.pdf
LISTE2 += ../GNU/RLvtotCZ.pdf
LISTE2 += ../GNU/SelfTrefCZ.pdf
LISTE2 += ../GNU/W12compareCZ.pdf

LISTE3 = ../GNU/Cap_FC_dataRU.pdf
LISTE3 += ../GNU/Cap_FR_dataRU.pdf
LISTE3 += ../GNU/Cap_FC_FR_dataRU.pdf
LISTE3 += ../GNU/CesrRU.pdf
LISTE3 += ../GNU/Cesr2RU.pdf
LISTE3 += ../GNU/Cesr_22nRU.pdf
LISTE3 += ../GNU/Cesr_22n_lowRU.pdf
LISTE3 += ../GNU/ComparatorAdjustRU.pdf
LISTE3 += ../GNU/Elco_esrRU.pdf
LISTE3 += ../GNU/frequency-ppmRU.pdf
LISTE3 += ../GNU/induct328pRU.pdf
LISTE3 += ../GNU/m168res_allRU.pdf
LISTE3 += ../GNU/MegaAutoRU.pdf
LISTE3 += ../GNU/Mega1284RU.pdf
LISTE3 += ../GNU/Mega168allRU.pdf 
LISTE3 += ../GNU/Mega168capRU.pdf
LISTE3 += ../GNU/Mega168cap_optRU.pdf
LISTE3 += ../GNU/Mega328allRU.pdf
LISTE3 += ../GNU/Mega8capRU.pdf
LISTE3 += ../GNU/Mega8resRU.pdf
LISTE3 += ../GNU/res_esrRU.pdf
LISTE3 += ../GNU/RHvRU.pdf
LISTE3 += ../GNU/RLvhighRU.pdf
LISTE3 += ../GNU/RLvlowRU.pdf
LISTE3 += ../GNU/RLvtotRU.pdf
LISTE3 += ../GNU/SelfTrefRU.pdf
LISTE3 += ../GNU/W12compareRU.pdf

LISTE4 = ../GNU/Cap_FC_dataGE.pdf
LISTE4 += ../GNU/Cap_FR_dataGE.pdf
LISTE4 += ../GNU/Cap_FC_FR_dataGE.pdf
LISTE4 += ../GNU/CesrGE.pdf
LISTE4 += ../GNU/Cesr2GE.pdf
LISTE4 += ../GNU/Cesr_22nGE.pdf
LISTE4 += ../GNU/Cesr_22n_lowGE.pdf
LISTE4 += ../GNU/ComparatorAdjustGE.pdf
LISTE4 += ../GNU/Elco_esrGE.pdf
LISTE4 += ../GNU/frequency-ppmGE.pdf
LISTE4 += ../GNU/induct328pGE.pdf
LISTE4 += ../GNU/m168res_allGE.pdf
LISTE4 += ../GNU/MegaAutoGE.pdf
LISTE4 += ../GNU/Mega1284GE.pdf
LISTE4 += ../GNU/Mega168allGE.pdf 
LISTE4 += ../GNU/Mega168capGE.pdf
LISTE4 += ../GNU/Mega168cap_optGE.pdf
LISTE4 += ../GNU/Mega328allGE.pdf
LISTE4 += ../GNU/Mega8capGE.pdf
LISTE4 += ../GNU/Mega8resGE.pdf
LISTE4 += ../GNU/res_esrGE.pdf
LISTE4 += ../GNU/RHvGE.pdf
LISTE4 += ../GNU/RLvhighGE.pdf
LISTE4 += ../GNU/RLvlowGE.pdf
LISTE4 += ../GNU/RLvtotGE.pdf
LISTE4 += ../GNU/SelfTrefGE.pdf
LISTE4 += ../GNU/W12compareGE.pdf


LISTE21 += ../FIG/port.pdf ../FIG/ResistormessH1.pdf ../FIG/ResistormessH2.pdf ../FIG/ResistormessL1.pdf
LISTE21 += ../FIG/ResistormessL2.pdf ../FIG/terminal.pdf
LISTE21 += ../FIG/Comparat.pdf ../FIG/Test2.pdf ../FIG/Test7.pdf ../FIG/Test8.pdf ../FIG/Bigcap.pdf ../FIG/Cap_residV.pdf
LISTE21 += ../FIG/PNPcc.pdf ../FIG/PNPce.pdf ../FIG/NPNce.pdf ../FIG/ttester.pdf ../FIG/t644tester.pdf ../FIG/relay_addon.pdf
LISTE21 += ../FIG/relay_um_addon.pdf ../FIG/diode_addon.pdf ../FIG/zener_exp.pdf ../FIG/Frequency_addon.pdf ../FIG/t1280tester.pdf
LISTE21 += ../FIG/Inductance.pdf ../FIG/JFETcd.pdf ../FIG/Cap_equiv.pdf ../FIG/Cap_esr.pdf ../FIG/Cap_esr2.pdf ../FIG/Cap_esr2_timing.pdf
LISTE21 += ../FIG/CheckSemi1.pdf ../FIG/CheckSemi2.pdf ../FIG/CheckSemi3.pdf
LISTE21 += ../FIG/rotary_extension.pdf ../FIG/rotary_encoder.pdf	../FIG/rotary_bouncing.pdf
LISTE21 += ../FIG/Fish8840.pdf ../FIG/ST7565lcd.pdf ../FIG/ST7920interface.pdf ../FIG/ST7108serial164.pdf
LISTE21 += ../FIG/ST7108serial595.pdf ../FIG/ST7108serial164_644.pdf ../FIG/ST7108serial595_644.pdf ../FIG/SSD1306_I2C.pdf
LISTE21 += ../FIG/sampling.pdf 
LISTE21 += ../FIG/GPS_UP501.pdf ../FIG/GPS_GNS701.pdf

LISTE50 = ../FIG/BJT_AD161.pdf ../FIG/BJT_AD162.pdf ../FIG/BJT_BC639.pdf ../FIG/BJT_BC640.pdf ../FIG/BJT_BU508D.pdf
LISTE50 += ../FIG/BJT_BC516.pdf ../FIG/BJT_BC517.pdf ../FIG/BJT_BDV64.pdf ../FIG/BJT_BDV65.pdf
LISTE50 += ../FIG/JFET_BF245.pdf ../FIG/JFET_J175.pdf ../FIG/MOS_BSS169.pdf ../FIG/MOS_BUZ71.pdf ../FIG/MOS_IRF5305.pdf

all: ttester.pdf ttinfo.pdf
	
../GNU/Cap_FC_dataEN.pdf: ../GNU/Cap_FC_data.gnu ../GNU/Cap6_FC_ESR.dat ../GNU/Cap16_FC_ESR.dat ../GNU/Cap35_FC_ESR.dat ../GNU/Cap63_FC_ESR.dat
	gnuplot ../GNU/Cap_FC_data.gnu
../GNU/Cap_FC_FR_dataEN.pdf: ../GNU/Cap_FC_FR_data.gnu ../GNU/Cap25_FC_ESR.dat ../GNU/Cap25_FR_ESR.dat
	gnuplot ../GNU/Cap_FC_FR_data.gnu
../GNU/Cap_FR_dataEN.pdf: ../GNU/Cap_FR_data.gnu ../GNU/Cap6_FR_ESR.dat ../GNU/Cap16_FR_ESR.dat ../GNU/Cap35_FR_ESR.dat ../GNU/Cap63_FR_ESR.dat
	gnuplot ../GNU/Cap_FR_data.gnu
../GNU/CesrEN.pdf: ../GNU/Cesr.gnu ../GNU/Cesr_all.dat
	gnuplot ../GNU/Cesr.gnu
../GNU/Cesr2EN.pdf: ../GNU/Cesr2.gnu ../GNU/Cesr2_all.dat
	gnuplot ../GNU/Cesr2.gnu
../GNU/Cesr_22nEN.pdf: ../GNU/Cesr_22n.gnu ../GNU/Cesr_22n.dat
	gnuplot ../GNU/Cesr_22n.gnu
../GNU/Cesr_22n_lowEN.pdf: ../GNU/Cesr_22n_low.gnu ../GNU/Cesr_22n_low.dat
	gnuplot ../GNU/Cesr_22n_low.gnu
../GNU/ComparatorAdjustEN.pdf: ../GNU/comparator_diff.gnu ../GNU/comparator_cap.dat
	gnuplot ../GNU/comparator_diff.gnu
../GNU/Elco_esrEN.pdf: ../GNU/Elco_esr.gnu ../GNU/Elco_esr.dat
	gnuplot ../GNU/Elco_esr.gnu
../GNU/frequency-ppmEN.pdf: ../GNU/frequency-ppm.gnu ../GNU/frequency-ppm.dat
	gnuplot ../GNU/frequency-ppm.gnu
../GNU/induct328pEN.pdf: ../GNU/inductors.gnu ../GNU/inductors.dat
	gnuplot ../GNU/inductors.gnu
../GNU/Mega1284EN.pdf: ../GNU/capmess1284.gnu ../GNU/capmess1284.dat
	gnuplot ../GNU/capmess1284.gnu
../GNU/m168res_allEN.pdf: ../GNU/rmess_all.gnu ../GNU/rmess-all.dat ../GNU/rmess-autocal.dat
	gnuplot ../GNU/rmess_all.gnu
../GNU/MegaAutoEN.pdf: ../GNU/capmessAUTO.gnu ../GNU/capmessAUTO.dat
	gnuplot ../GNU/capmessAUTO.gnu
../GNU/Mega168allEN.pdf: ../GNU/capmess168all.gnu ../GNU/capmess168-all.dat ../GNU/capmess168-autocal.dat
	gnuplot ../GNU/capmess168all.gnu
../GNU/Mega168capEN.pdf: ../GNU/capmess168.gnu ../GNU/capmess168.dat
	gnuplot ../GNU/capmess168.gnu
../GNU/Mega168cap_optEN.pdf: ../GNU/capmessopt168.gnu ../GNU/capmess168-3.dat
	gnuplot ../GNU/capmessopt168.gnu
../GNU/Mega328allEN.pdf: ../GNU/capmess328all.gnu ../GNU/capmess328-all.dat ../GNU/capmess328-autocal.dat
	gnuplot ../GNU/capmess328all.gnu
../GNU/Mega8resEN.pdf: ../GNU/rmess.gnu ../GNU/rmess.dat
	gnuplot ../GNU/rmess.gnu
../GNU/Mega8capEN.pdf: ../GNU/capmess8.gnu ../GNU/capmess8.dat ../GNU/capmessorig.dat
	gnuplot ../GNU/capmess8.gnu
../GNU/res_esrEN.pdf: ../GNU/rmess_esr.gnu ../GNU/rmess-esr.dat
	gnuplot ../GNU/rmess_esr.gnu
../GNU/RHvEN.pdf: ../GNU/RHv.gnu
	gnuplot $<
../GNU/RLvhighEN.pdf: ../GNU/RLvhigh.gnu
	gnuplot $<
../GNU/RLvlowEN.pdf: ../GNU/RLvlow.gnu
	gnuplot $<
../GNU/RLvtotEN.pdf: ../GNU/RLvtot.gnu
	gnuplot $<
../GNU/SelfTrefEN.pdf: ../GNU/selftest.gnu ../GNU/selftest.dat
	gnuplot ../GNU/selftest.gnu
../GNU/W12compareEN.pdf: ../GNU/W12compare.gnu ../GNU/W12_18nF.dat ../GNU/W12_20nF.dat
	gnuplot ../GNU/W12compare.gnu
	
../GNU/Cap_FC_dataCZ.pdf: ../GNU/Cap_FC_data.gnu ../GNU/Cap6_FC_ESR.dat ../GNU/Cap16_FC_ESR.dat ../GNU/Cap35_FC_ESR.dat ../GNU/Cap63_FC_ESR.dat
	gnuplot ../GNU/Cap_FC_data.gnu
../GNU/Cap_FC_FR_dataCZ.pdf: ../GNU/Cap_FC_FR_data.gnu ../GNU/Cap25_FC_ESR.dat ../GNU/Cap25_FR_ESR.dat
	gnuplot ../GNU/Cap_FC_FR_data.gnu
../GNU/Cap_FR_dataCZ.pdf: ../GNU/Cap_FR_data.gnu ../GNU/Cap6_FR_ESR.dat ../GNU/Cap16_FR_ESR.dat ../GNU/Cap35_FR_ESR.dat ../GNU/Cap63_FR_ESR.dat
	gnuplot ../GNU/Cap_FR_data.gnu
../GNU/CesrCZ.pdf: ../GNU/Cesr.gnu ../GNU/Cesr_all.dat
	gnuplot ../GNU/Cesr.gnu
../GNU/Cesr2CZ.pdf: ../GNU/Cesr2.gnu ../GNU/Cesr2_all.dat
	gnuplot ../GNU/Cesr2.gnu
../GNU/Cesr_22nCZ.pdf: ../GNU/Cesr_22n.gnu ../GNU/Cesr_22n.dat
	gnuplot ../GNU/Cesr_22n.gnu
../GNU/Cesr_22n_lowCZ.pdf: ../GNU/Cesr_22n_low.gnu ../GNU/Cesr_22n_low.dat
	gnuplot ../GNU/Cesr_22n_low.gnu
../GNU/ComparatorAdjustCZ.pdf: ../GNU/comparator_diff.gnu ../GNU/comparator_cap.dat
	gnuplot ../GNU/comparator_diff.gnu
../GNU/Elco_esrCZ.pdf: ../GNU/Elco_esr.gnu ../GNU/Elco_esr.dat
	gnuplot ../GNU/Elco_esr.gnu
../GNU/frequency-ppmCZ.pdf: ../GNU/frequency-ppm.gnu ../GNU/frequency-ppm.dat
	gnuplot ../GNU/frequency-ppm.gnu
../GNU/induct328pCZ.pdf: ../GNU/inductors.gnu ../GNU/inductors.dat
	gnuplot ../GNU/inductors.gnu
../GNU/Mega1284CZ.pdf: ../GNU/capmess1284.gnu ../GNU/capmess1284.dat
	gnuplot ../GNU/capmess1284.gnu
../GNU/m168res_allCZ.pdf: ../GNU/rmess_all.gnu ../GNU/rmess-all.dat ../GNU/rmess-autocal.dat
	gnuplot ../GNU/rmess_all.gnu
../GNU/MegaAutoCZ.pdf: ../GNU/capmessAUTO.gnu ../GNU/capmessAUTO.dat
	gnuplot ../GNU/capmessAUTO.gnu
../GNU/Mega168allCZ.pdf: ../GNU/capmess168all.gnu ../GNU/capmess168-all.dat ../GNU/capmess168-autocal.dat
	gnuplot ../GNU/capmess168all.gnu
../GNU/Mega168capCZ.pdf: ../GNU/capmess168.gnu ../GNU/capmess168.dat
	gnuplot ../GNU/capmess168.gnu
../GNU/Mega168cap_optCZ.pdf: ../GNU/capmessopt168.gnu ../GNU/capmess168-3.dat
	gnuplot ../GNU/capmessopt168.gnu
../GNU/Mega328allCZ.pdf: ../GNU/capmess328all.gnu ../GNU/capmess328-all.dat ../GNU/capmess328-autocal.dat
	gnuplot ../GNU/capmess328all.gnu
../GNU/Mega8resCZ.pdf: ../GNU/rmess.gnu ../GNU/rmess.dat
	gnuplot ../GNU/rmess.gnu
../GNU/Mega8capCZ.pdf: ../GNU/capmess8.gnu ../GNU/capmess8.dat ../GNU/capmessorig.dat
	gnuplot ../GNU/capmess8.gnu
../GNU/res_esrCZ.pdf: ../GNU/rmess_esr.gnu ../GNU/rmess-esr.dat
	gnuplot ../GNU/rmess_esr.gnu
../GNU/RHvCZ.pdf: ../GNU/RHv.gnu
	gnuplot $<
../GNU/RLvhighCZ.pdf: ../GNU/RLvhigh.gnu
	gnuplot $<
../GNU/RLvlowCZ.pdf: ../GNU/RLvlow.gnu
	gnuplot $<
../GNU/RLvtotCZ.pdf: ../GNU/RLvtot.gnu
	gnuplot $<
../GNU/SelfTrefCZ.pdf: ../GNU/selftest.gnu ../GNU/selftest.dat
	gnuplot ../GNU/selftest.gnu
../GNU/W12compareCZ.pdf: ../GNU/W12compare.gnu ../GNU/W12_18nF.dat ../GNU/W12_20nF.dat
	gnuplot ../GNU/W12compare.gnu
	
../GNU/Cap_FC_dataRU.pdf: ../GNU/Cap_FC_data.gnu ../GNU/Cap6_FC_ESR.dat ../GNU/Cap16_FC_ESR.dat ../GNU/Cap35_FC_ESR.dat ../GNU/Cap63_FC_ESR.dat
	gnuplot ../GNU/Cap_FC_data.gnu
../GNU/Cap_FC_FR_dataRU.pdf: ../GNU/Cap_FC_FR_data.gnu ../GNU/Cap25_FC_ESR.dat ../GNU/Cap25_FR_ESR.dat
	gnuplot ../GNU/Cap_FC_FR_data.gnu
../GNU/Cap_FR_dataRU.pdf: ../GNU/Cap_FR_data.gnu ../GNU/Cap6_FR_ESR.dat ../GNU/Cap16_FR_ESR.dat ../GNU/Cap35_FR_ESR.dat ../GNU/Cap63_FR_ESR.dat
	gnuplot ../GNU/Cap_FR_data.gnu
../GNU/CesrRU.pdf: ../GNU/Cesr.gnu ../GNU/Cesr_all.dat
	gnuplot ../GNU/Cesr.gnu
../GNU/Cesr2RU.pdf: ../GNU/Cesr2.gnu ../GNU/Cesr2_all.dat
	gnuplot ../GNU/Cesr2.gnu
../GNU/Cesr_22nRU.pdf: ../GNU/Cesr_22n.gnu ../GNU/Cesr_22n.dat
	gnuplot ../GNU/Cesr_22n.gnu
../GNU/Cesr_22n_lowRU.pdf: ../GNU/Cesr_22n_low.gnu ../GNU/Cesr_22n_low.dat
	gnuplot ../GNU/Cesr_22n_low.gnu
../GNU/ComparatorAdjustRU.pdf: ../GNU/comparator_diff.gnu ../GNU/comparator_cap.dat
	gnuplot ../GNU/comparator_diff.gnu
../GNU/Elco_esrRU.pdf: ../GNU/Elco_esr.gnu ../GNU/Elco_esr.dat
	gnuplot ../GNU/Elco_esr.gnu
../GNU/frequency-ppmRU.pdf: ../GNU/frequency-ppm.gnu ../GNU/frequency-ppm.dat
	gnuplot ../GNU/frequency-ppm.gnu
../GNU/induct328pRU.pdf: ../GNU/inductors.gnu ../GNU/inductors.dat
	gnuplot ../GNU/inductors.gnu
../GNU/Mega1284RU.pdf: ../GNU/capmess1284.gnu ../GNU/capmess1284.dat
	gnuplot ../GNU/capmess1284.gnu
../GNU/m168res_allRU.pdf: ../GNU/rmess_all.gnu ../GNU/rmess-all.dat ../GNU/rmess-autocal.dat
	gnuplot ../GNU/rmess_all.gnu
../GNU/MegaAutoRU.pdf: ../GNU/capmessAUTO.gnu ../GNU/capmessAUTO.dat
	gnuplot ../GNU/capmessAUTO.gnu
../GNU/Mega168allRU.pdf: ../GNU/capmess168all.gnu ../GNU/capmess168-all.dat ../GNU/capmess168-autocal.dat
	gnuplot ../GNU/capmess168all.gnu
../GNU/Mega168capRU.pdf: ../GNU/capmess168.gnu ../GNU/capmess168.dat
	gnuplot ../GNU/capmess168.gnu
../GNU/Mega168cap_optRU.pdf: ../GNU/capmessopt168.gnu ../GNU/capmess168-3.dat
	gnuplot ../GNU/capmessopt168.gnu
../GNU/Mega328allRU.pdf: ../GNU/capmess328all.gnu ../GNU/capmess328-all.dat ../GNU/capmess328-autocal.dat
	gnuplot ../GNU/capmess328all.gnu
../GNU/Mega8resRU.pdf: ../GNU/rmess.gnu ../GNU/rmess.dat
	gnuplot ../GNU/rmess.gnu
../GNU/Mega8capRU.pdf: ../GNU/capmess8.gnu ../GNU/capmess8.dat ../GNU/capmessorig.dat
	gnuplot ../GNU/capmess8.gnu
../GNU/res_esrRU.pdf: ../GNU/rmess_esr.gnu ../GNU/rmess-esr.dat
	gnuplot ../GNU/rmess_esr.gnu
../GNU/RHvRU.pdf: ../GNU/RHv.gnu
	gnuplot $<
../GNU/RLvhighRU.pdf: ../GNU/RLvhigh.gnu
	gnuplot $<
../GNU/RLvlowRU.pdf: ../GNU/RLvlow.gnu
	gnuplot $<
../GNU/RLvtotRU.pdf: ../GNU/RLvtot.gnu
	gnuplot $<
../GNU/SelfTrefRU.pdf: ../GNU/selftest.gnu ../GNU/selftest.dat
	gnuplot ../GNU/selftest.gnu
../GNU/W12compareRU.pdf: ../GNU/W12compare.gnu ../GNU/W12_18nF.dat ../GNU/W12_20nF.dat
	gnuplot ../GNU/W12compare.gnu

../FIG/port.pdf: ../FIG/port.fig
	fig2pdf --nogv $<
../FIG/terminal.pdf: ../FIG/terminal.fig
	fig2pdf --nogv $<
../FIG/ResistormessH1.pdf: ../FIG/ResistormessH1.fig
	fig2pdf --nogv $<
../FIG/ResistormessH2.pdf: ../FIG/ResistormessH2.fig
	fig2pdf --nogv $<
../FIG/ResistormessL1.pdf: ../FIG/ResistormessL1.fig
	fig2pdf --nogv $<
../FIG/ResistormessL2.pdf: ../FIG/ResistormessL2.fig
	fig2pdf --nogv $<
../FIG/Bigcap.pdf: ../FIG/Bigcap.fig
	fig2pdf --nogv $<
../FIG/Cap_residV.pdf: ../FIG/Cap_residV.fig
	fig2pdf --nogv $<
../FIG/Comparat.pdf: ../FIG/Comparat.fig
	fig2pdf --nogv $<
../FIG/Test2.pdf: ../FIG/Test2.fig
	fig2pdf --nogv $<
../FIG/Test7.pdf: ../FIG/Test7.fig
	fig2pdf --nogv $<
../FIG/Test8.pdf: ../FIG/Test8.fig
	fig2pdf --nogv $<
../FIG/PNPcc.pdf: ../FIG/PNPcc.fig
	fig2pdf --nogv $<
../FIG/PNPce.pdf: ../FIG/PNPce.fig
	fig2pdf --nogv $<
../FIG/NPNce.pdf: ../FIG/NPNce.fig
	fig2pdf --nogv $<
../FIG/JFETcd.pdf: ../FIG/JFETcd.fig
	fig2pdf --nogv $<
../FIG/ttester.pdf: ../FIG/ttester.fig
	fig2pdf --nogv $<
../FIG/t644tester.pdf: ../FIG/t644tester.fig
	fig2pdf --nogv $<
../FIG/t1280tester.pdf: ../FIG/t1280tester.fig
	fig2pdf --nogv $<
../FIG/relay_addon.pdf: ../FIG/relay_addon.fig
	fig2pdf --nogv $<
../FIG/relay_um_addon.pdf: ../FIG/relay_um_addon.fig
	fig2pdf --nogv $<
../FIG/diode_addon.pdf: ../FIG/diode_addon.fig
	fig2pdf --nogv $<
../FIG/Frequency_addon.pdf: ../FIG/Frequency_addon.fig
	fig2pdf --nogv $<
../FIG/zener_exp.pdf: ../FIG/zener_exp.fig
	fig2pdf --nogv $<
../FIG/Inductance.pdf: ../FIG/Inductance.fig
	fig2pdf --nogv $<
../FIG/Cap_equiv.pdf: ../FIG/Cap_equiv.fig
	fig2pdf --nogv $<
../FIG/Cap_esr.pdf: ../FIG/Cap_esr.fig
	fig2pdf --nogv $<
../FIG/Cap_esr2.pdf: ../FIG/Cap_esr2.fig
	fig2pdf --nogv $<
../FIG/Cap_esr2_timing.pdf: ../FIG/Cap_esr2_timing.fig
	fig2pdf --nogv $<
../FIG/CheckSemi1.pdf: ../FIG/CheckSemi1.fig
	fig2pdf --nogv $<
../FIG/CheckSemi2.pdf: ../FIG/CheckSemi2.fig
	fig2pdf --nogv $<
../FIG/CheckSemi3.pdf: ../FIG/CheckSemi3.fig
	fig2pdf --nogv $<

../FIG/BJT_AD161.pdf: ../FIG/BJT_AD161.fig
	fig2pdf --nogv $<
../FIG/BJT_AD162.pdf: ../FIG/BJT_AD162.fig
	fig2pdf --nogv $<
../FIG/BJT_BC639.pdf: ../FIG/BJT_BC639.fig
	fig2pdf --nogv $<
../FIG/BJT_BC640.pdf: ../FIG/BJT_BC640.fig
	fig2pdf --nogv $<
../FIG/BJT_BU508D.pdf: ../FIG/BJT_BU508D.fig
	fig2pdf --nogv $<
../FIG/BJT_BC516.pdf: ../FIG/BJT_BC516.fig
	fig2pdf --nogv $<
../FIG/BJT_BC517.pdf: ../FIG/BJT_BC517.fig
	fig2pdf --nogv $<
../FIG/BJT_BDV64.pdf: ../FIG/BJT_BDV64.fig
	fig2pdf --nogv $<
../FIG/BJT_BDV65.pdf: ../FIG/BJT_BDV65.fig
	fig2pdf --nogv $<
../FIG/JFET_BF245.pdf: ../FIG/JFET_BF245.fig
	fig2pdf --nogv $<
../FIG/JFET_J175.pdf: ../FIG/JFET_J175.fig
	fig2pdf --nogv $<
../FIG/MOS_BSS169.pdf: ../FIG/MOS_BSS169.fig
	fig2pdf --nogv $<
../FIG/MOS_BUZ71.pdf: ../FIG/MOS_BUZ71.fig
	fig2pdf --nogv $<
../FIG/MOS_IRF5305.pdf: ../FIG/MOS_IRF5305.fig
	fig2pdf --nogv $<
../FIG/GPS_UP501.pdf: ../FIG/GPS_UP501.fig
	fig2pdf --nogv $<
../FIG/GPS_GNS701.pdf: ../FIG/GPS_GNS701.fig
	fig2pdf --nogv $<
../FIG/rotary_encoder.pdf: ../FIG/rotary_encoder.fig
	fig2pdf --nogv $<
../FIG/rotary_extension.pdf: ../FIG/rotary_extension.fig
	fig2pdf --nogv $<
../FIG/rotary_bouncing.pdf: ../FIG/rotary_bouncing.fig
	fig2pdf --nogv $<
../FIG/Fish8840.pdf: ../FIG/Fish8840.fig
	fig2pdf --nogv $<
../FIG/ST7565lcd.pdf: ../FIG/ST7565lcd.fig
	fig2pdf --nogv $<
../FIG/ST7920interface.pdf: ../FIG/ST7920interface.fig
	fig2pdf --nogv $<
../FIG/ST7108serial164.pdf: ../FIG/ST7108serial164.fig
	fig2pdf --nogv $<
../FIG/ST7108serial595.pdf: ../FIG/ST7108serial595.fig
	fig2pdf --nogv $<
../FIG/ST7108serial164_644.pdf: ../FIG/ST7108serial164_644.fig
	fig2pdf --nogv $<
../FIG/ST7108serial595_644.pdf: ../FIG/ST7108serial595_644.fig
	fig2pdf --nogv $<
../FIG/SSD1306_I2C.pdf: ../FIG/SSD1306_I2C.fig
	fig2pdf --nogv $<
../FIG/sampling.pdf: ../FIG/sampling.fig
	fig2pdf --nogv $<

TEXLIST1 =  00-preface.tex 10-features.tex 20-hardware.tex 30-manual.tex 40-configuring.tex
TEXLIST1 += 50-measurement.tex 51-semicon.tex 52-resistors.tex 53-capacitors.tex 54-inductors.tex 55-selftest.tex 56-frequency.tex
TEXLIST1 += 60-generators.tex 70-errors.tex 80-special.tex 90-todo.tex

TEXLIST50 = BJT-transistors.tex MOS-transistors.tex

.PHONY: ttester.pdf
ttester.pdf: ttester.tex $(LISTE1) $(LISTE2) $(LISTE3) $(LISTE4) $(LISTE21) $(TEXLIST1) Makefile
	pdflatex --shell-escape ttester.tex 

ttinfo.pdf: ttinfo.tex $(LISTE50) $(TEXLIST50) Makefile
	pdflatex --shell-escape ttinfo.tex
	pdflatex --shell-escape ttinfo.tex
clean:
	rm -f $(LISTE1) ../GNU/*EN.pdf $(LISTE2) ../GNU/*CZ.pdf $(LISTE3) ../GNU/*RU.pdf $(LISTE4) ../GNU/*GE.pdf $(LISTE21) $(LISTE50)
steril:
	rm  -f $(LISTE1) ../GNU/*EN.pdf $(LISTE2) ../GNU/*CZ.pdf $(LISTE3) ../GNU/*RU.pdf $(LISTE4) ../GNU/*GE.pdf *.aux 
